import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";

import NextUIProvider from "@/providers/NextUIProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import ThemeProvider from "@/providers/ThemeProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import "./globals.css";

const font = Poppins({ weight: "400", subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Whalesbook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ReactQueryProvider>
          <NextUIProvider>
            <ThemeProvider>
              <div id="send-code-button" />
              <Toaster position="top-right" />
              {children}
            </ThemeProvider>
          </NextUIProvider>
          {/* <ReactQueryDevtools /> */}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
